

development:
    webhost: "https://googledemo0303-rtr77.c9users.io/"
    connect:
        user_name: "demo@remotelock.com"
        client: "5878a16492f24323c2ef3d9c970fd9086fbf1568724afb8065dc3180fd4bdeac"
        secret: "721cbf34fc3ff3d5f9033d3dd765fb351095c75b7cde403533295b3c495dd4cd"
        uuid: "b9fdcd0c-3713-4043-b7a6-3501bc9832ad"
    google:
        user_name: "kke.remotelock@gmail.com"
        client: "404180661728-qotv9so92qt4pp6s7v9jlmheik6bespe.apps.googleusercontent.com"
        secret: "ZS6_pVing3DInTzpJ7c3QpJ"
        calendar_id: "g8ukpibvlfle41hplt1g3rplu0@group.calendar.google.com"
        google-site-verification: '<meta name="google-site-verification" content="mwXIsAM7T9kSRBW3kjGPEP7LkI_CATVt0eJgBTmK-es" />'

#APP_CONFIG["connect"]["client"]
    
production:
    webhost: "https://kkeapidemo2.herokuapp.com/"
    connect:
        user_name: "demo@remotelock.com"
        client: "5878a16492f24323c2ef3d9c970fd9086fbf1568724afb8065dc3180fd4bdeac"
        secret: "721cbf34fc3ff3d5f9033d3dd765fb351095c75b7cde403533295b3c495dd4cd"
        uuid: "b9fdcd0c-3713-4043-b7a6-3501bc9832ad"
    google:
        user_name: "kke.remotelock@gmail.com"
        client: "404180661728-qotv9so92qt4pp6s7v9jlmheik6bespe.apps.googleusercontent.com"
        secret: "ZS6_pVing3DInTzpJ7c3QpJ"
        calendar_id: "g8ukpibvlfle41hplt1g3rplu0@group.calendar.google.com"
        google-site-verification: '<meta name="google-site-verification" content="mwXIsAM7T9kSRBW3kjGPEP7LkI_CATVt0eJgBTmK-es" />'
