development:
    #tsukamoto-san-settings
    #webhost: "https://googledemo0303-rtr77.c9users.io/"
    #connect:
    #    user_name: "demo@remotelock.com"
    #    client: "5878a16492f24323c2ef3d9c970fd9086fbf1568724afb8065dc3180fd4bdeac"
    #    secret: "721cbf34fc3ff3d5f9033d3dd765fb351095c75b7cde403533295b3c495dd4cd"
    #    uuid: "b9fdcd0c-3713-4043-b7a6-3501bc9832ad"
    #google:
    #    client: "404180661728-qotv9so92qt4pp6s7v9jlmheik6bespe.apps.googleusercontent.com"
    #    secret: "_ZS6_pVing3DInTzpJ7c3QpJ"
    #    calendar_id: "g8ukpibvlfle41hplt1g3rplu0@group.calendar.google.com"
    #    google-site-verification: '<meta name="google-site-verification" content="mwXIsAM7T9kSRBW3kjGPEP7LkI_CATVt0eJgBTmK-es" />'

    #tsunai-setteings
    webhost: "https://google-demo-yumikotsunai.c9users.io/"
    connect:
        user_name: "demo@remotelock.com"
        client: "248b4559af5bbdf84998f5c092bc8d9fac784712f28009168c0a1579818aef47"
        secret: "b88822e0976b6e6a9fb0096a3b1c860b12f9a405fd2d0597a1d60cf68473ac46"
        uuid: "c0ee6144-3734-4e11-b4be-c35e4abdc05c"
    google:
        #user_name: "yumikokke@gmail.com"
        user_name: "A"
        client: "841258018012-jqn06q4ifmfvbj5ip42rvtemetcga7oj.apps.googleusercontent.com"
        secret: "HuQ43i5_NiqOeOIZca4oJttJ"
        calendar_id: "i8a77r26f9pu967g3pqpubv0ng@group.calendar.google.com"
        google-site-verification: '<meta name="google-site-verification" content="yXHeDhmd4GXL3-G-H0JweJuPZspzF_8IPRkmmBqC2Iw" />'
    #google:
    #    user_name: "kke.remotelock@gmail.com"
    #    client: "404180661728-qotv9so92qt4pp6s7v9jlmheik6bespe.apps.googleusercontent.com"
    #    secret: "_ZS6_pVing3DInTzpJ7c3QpJ"
    #    calendar_id: "g8ukpibvlfle41hplt1g3rplu0@group.calendar.google.com"
    #    google-site-verification: '<meta name="google-site-verification" content="mwXIsAM7T9kSRBW3kjGPEP7LkI_CATVt0eJgBTmK-es" />'
    
#APP_CONFIG["connect"]["client"]
    
production:
    webhost: "https://kkeapidemo.herokuapp.com/"
    #webhost: "https://google-demo-yumikotsunai.c9users.io/"
    connect:
        user_name: "demo@remotelock.com"
        client: "86169dfc79da7ce9000a1d2f37dcb95f96d9b3bb03bf32e57b540cbaedbf0989"
        secret: "1bfa525b96c3102c65d1f2be4abfa541f0b57ee17ac92dffbb9abf6417740c23"
        uuid: "8a2f4c49-1c3a-41e4-bfa8-8dcde063ee07"
    google:
        user_name: "kke.remotelock@gmail.com"
        client: "404180661728-qotv9so92qt4pp6s7v9jlmheik6bespe.apps.googleusercontent.com"
        secret: "_ZS6_pVing3DInTzpJ7c3QpJ"
        calendar_id: "g8ukpibvlfle41hplt1g3rplu0@group.calendar.google.com"
        #google-site-verification: '<meta name="google-site-verification" content="mwXIsAM7T9kSRBW3kjGPEP7LkI_CATVt0eJgBTmK-es" />'
        #↑apidemo2 ↓apidemo
        google-site-verification: '<meta name="google-site-verification" content="PZDi1CWGW25rzFiv5I5OBN2btplsGK2ErW3jxVZ8DsQ" />'
